@echo off
echo Starting PortfolioAI Development Environment...
echo.

echo Starting Express API Server on port 3000...
start /B node server.js

echo Waiting for API server to start...
timeout /t 2 /nobreak > nul

echo Starting Vite Development Server on port 8080...
npm run dev
